[colors]
ansi = [
    '#000000',
    '#ca1243',
    '#50a14f',
    '#c18401',
    '#4078f2',
    '#a626a4',
    '#3f953a',
    '#bbbbbb',
]
background = '#fafafa'
brights = [
    '#000000',
    '#ca1243',
    '#50a14f',
    '#c18401',
    '#4078f2',
    '#a626a4',
    '#3f953a',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#2a2b33'
foreground = '#2a2b33'
selection_bg = '#bbbbbb'
selection_fg = '#2a2c33'

[colors.indexed]

[metadata]
name = 'jmarple one'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'

